website/models.py
from flask_login import UserMixin
from . import db
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    datehi = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

# Create User Database
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(30))
    firstname = db.Column(db.String(30))
    lastname = db.Column(db.String(30))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


# inititialize SQLAlchemy so we can use it later in our models
db = SQLAlchemy()
DB_NAME = 'database.db'


def create_app():

    app = Flask(__name__)
    app.secret_key = 'wadnjkwadn jwdjanwd'

    # Ensure templates are auto-reloaded
    app.config["TEMPLATES_AUTO_RELOAD"] = True
    app.config["SQLALCHEMY_DATABASE_URI"] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)


    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)


    @login_manager.user_loader
    def get(id):
        return User.query.get(id)


    # blueprint for the auth routes
    from .auth import auth
    from .views import views
    from .models import User, Note

    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(views, url_prefix='/')

    with app.app_context():
        db.create_all()
    app.static_folder = 'static'

    return app

def create_database(app):       
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('DATABASE CREATED!!!!!!!!!!')

website/auth.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from .models import User
from flask_login import login_user, login_required, logout_user, current_user
from . import db
from time import sleep

auth = Blueprint('auth', __name__)

@auth.route('/books', methods=['GET', 'POST'])
def books():
    if request.method == 'POST':
        return
    else:
        return render_template('books.html')

@auth.route('/login/', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        # login_user(user)
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category='success')
                login_user(user, remember=True)
                sleep(2)
                return redirect(url_for('views.index'))
            else:
                flash("Incorrect password. Please try again.", category='error')
                return redirect(url_for('auth.login'))
        else:
            flash("Email does not exist. Please try again.", category='error')
            return redirect(url_for('auth.login'))

    else:
        return render_template('login.html')

@auth.route('/register', methods=['GET', 'POST'])
def register():

    if request.method == 'POST':
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password = request.form.get('password')
        confirm = request.form.get('confirm')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('This email is already associated with an account. Please log in.', category='error')
            return redirect(url_for('auth.register'))

        else:
            if len(email) < 4:
                flash('Email must be greater than 3 characters', category='error')
                return redirect(url_for('auth.register'))

            elif len(firstname) < 2:
                flash('First name must have a minimum of 2 characters', category='error')
                return redirect(url_for('auth.register'))
            elif password != confirm:
                flash('Passwords do not match. Try again.', category='error')
                return redirect(url_for('auth.register'))
            elif len(password) < 8:
                flash('Password must have a minimum of 8 characters.', category='error')
                return redirect(url_for('auth.register'))

            else:
                new_user = User(email=email, firstname=firstname, lastname=lastname, password=generate_password_hash(password, method='sha256'))
                flash('Account created.', category='success')
                sleep(3)
                # new_user = User.query.filter_by(email=email).first()
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                return redirect(url_for('views.index'))
    else:
        return render_template('register.html', user=current_user)

@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    sleep(2)
    return redirect(url_for('auth.login'))

website/main.py
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy
import time
from website import create_app

app = create_app()


if __name__ == '__main__':
    app.run(debug=True)

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

views = Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template('index.html', user=current_user)

website/templates/books.html
{% extends "layout.html" %}

{% block title %}
    My Books
{% endblock %}

{% block main %}
    <div>Books</div>
{% endblock %}

website/templates/index.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}
        <script>
             function modal(id) {
                const buttons = document.getElementsByClassName('more-info');
                const modal = document.querySelector('.modal');
                const modalClose = document.querySelector('.modal-close-button');

                for (let button of buttons) {
                    button.addEventListener('click', function (e) {
                        if (event.target.tagName == 'A') {
                            const item = e.target.parentElement;
                            const first = item.parentElement;
                            const h3 = item.querySelector('.book-title').innerHTML;
                            const author = item.querySelector('#book-author').innerHTML;
                            const publishDate = item.querySelector('#book-published').innerHTML;
                            const pg = item.querySelector('#book-pg-count').innerHTML;
                            const desc = item.querySelector('.book-description').innerHTML;
                            const img = first.querySelector('.book-cover').innerHTML;
                            // modal.querySelector('.modal-title').innerHTML = h3;
                            modal.querySelector('.modal-body').innerHTML = 
                            `
                            <div class="modal-img">${img}</div>
                            <div class="modal-book-title">${h3}</div>
                            <div class="modal-info">
                                <div>${author}</div>
                                <div>${publishDate}</div>
                                <div>${pg}</div>
                                <div class="modal-desc"><span class="card-text">Description:</span> ${desc}</div>
                            </div>
                            `
                            
                                    
                            console.log(item);
                            openModal(modal);
                        }
                    })
                };

                modal.addEventListener('click', function (e) {
                    if (e.target == modal) {
                        openModal(modal);
                    }
                })

                modalClose.addEventListener('click', closeModal);

                function openModal(modal) {
                    if (modal == null) return;
                    modal.classList.add('active');
                }
                function closeModal() {
                    if (modal == null) return;
                    modal.classList.remove('active');
                    
                }
            };
        </script>
        <div class="main-image d-flex align-items-center justify-content-center flex-column">
            <div class="search-container">
                <div class="search-header p-3">Find a book</div>
                    <div class="form-group search">
                        <input id="input-search" type="text" class="form-control" placeholder='"Lord of the Rings"'>
                        <button id="search" class="btn btn-secondary">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="book-list mt-5" style="display:none">
            <h2 class="text-center">Search Results</h2>
            <div class="results-container" id="search-results">

            </div>
        </div>
        <!-- MODAL -->
        <div class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title"></div>
                    <button class="modal-close-button">&times;</button>
                </div>
                <div class="modal-body">
                    <p></p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary add-book">Add to Shelf</p>
                </div>
            </div>
        </div>
        <!-- MODAL END -->
        <script src="static/script.js"></script>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anek+Latin:wght@500&family=Clicker+Script&family=Oleo+Script+Swash+Caps&family=Raleway&family=Sora:wght@400;700&display=swap" rel="stylesheet">
    <link href="/static/style.css" rel="stylesheet">
    

    <title>Virtual Bookshelf {% block title %} {% endblock %}</title>

</head>
<style>

</style>
<body class="bd-main">
    <nav class="bg-light border navbar navbar-expand-md navbar-light"> 
        <div class="container-fluid">
            <div class="justify-content-start">
                <a href="/"><img src="/static/images/book.png" alt="book" class='icon'></a>
                <a class="navbar-brand" href="/">BOOKHUB</a>
            </div>
                
            <ul class="nav justify-content-end">
                <li class="nav-item"></li>
                    <a href="{{url_for('views.index')}}" class="nav-link active">Find Books</a>
                {% if current_user.is_authenticated %}
                <li class="nav-item"></li>
                    <a href="{{url_for('auth.books')}}" class="nav-link">My Books</a>
                <li class="nav-item"></li>
                    <a href="{{url_for('auth.logout')}}" class="nav-link">Logout</a>
                {% else %}
                <li class="nav-item"></li>
                    <a href="{{url_for('auth.login')}}" class="nav-link">Login</a>
                <li class="nav-item"></li>
                    <a href="{{url_for('auth.register')}}" class="nav-link">Register</a>
                {% endif %}
                <div class="animation start-home"></div>
            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% else %}
    <div class="alert alert-success  alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <main class="text-center">
        {% block main %} 
            
        
        {% endblock %}
    </main>
</body>
</html>

website/templates/login.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <form action="{{url_for('auth.login')}}" method="post" class="g-3 pt-5">
        <div class="mb-3">
            <div class="fs-4 fw-light ms-1">Login</div>
        </div>
        <div class="mb-3 p-2">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="email" name="email" placeholder="Email Address" type="text" aria-required="">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="password" name="password" placeholder="Password" type="password">
        </div>
        <div class="mb-3">
            Don't have an account? <span><a href="{{url_for('auth.register')}}">Create an account.</a></span>
        </div>
        <button class=" btn btn-primary btn-dark" type="submit">Log In</button>
    </form>
    
{% endblock %}

website/templates/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block main %}
   
    <form action="{{url_for('auth.register')}}" method="post" class="g-3 pt-5">
        <div class="mb-3">
            <div class="fs-4 fw-light ms-1">Register</div>
        </div>
        <div class="mb-3">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="email" name="email" placeholder="Email" type="text">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="firstname" name="firstname" placeholder="First Name" type="text">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="lastname" name="lastname" placeholder="Last Name" type="text">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="password" name="password" placeholder="Password" type="password">
            <small class="form-text text-muted">Minimum of 8 characters.</small>
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="confirm" name="confirm" placeholder="Confirm Password" type="password">
        </div>
        <div class="mb-3">
            Already have an account? <span><a href="{{url_for('auth.login')}}"> Log in.</a></span>
        </div>
        <button class="btn btn-primary btn-dark" type="submit">Sign up</button>
    </form>
    
{% endblock %}